#version: '3.9'

services:
  db:
    container_name: postgres_database 
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=hw3_database_fastapi #Имя базы данных, к которой необходимо подключиться

  fastapi:
    build: .
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres_database/5432; do sleep 1; done; uvicorn app:fastapi_application --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@postgres_database:5432/hw3_database_fastapi
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
